# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: GATAIAN dominio Convenios 
  description: Este es el dominio de convenios para la app Recursos humanos GATAIAN
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    Convenio:
      type: object
      required: 
        - id
        - nit
        - nombre
        - descripcion
        - tipo
        - direcciones
      properties:
        id:
          description: este es el identificador interno unico del convenio
          type: integer
          format: int64
        nit:
          description: esta es la identificación del convenio
          type: string
        nombre:
          description: corresponde al nombre del convenio
          type: string
        descripcion:
          description: una descripcion simple de las labores del convenio
          type: string
        tipo:
          $ref: '#/components/schemas/TipoConvenio'
        direccion:
          type: array
          items:
            $ref: '#/components/schemas/Direccion'
        documentacionRequerida:
          type: array
          items:
            $ref: '#/components/schemas/DocumentacionRequerida'
            
    DocumentacionRequerida:
      type: object
      description: indica el documento que pide el convenio para afiliar un empleado
      required:
        - id
        - nombre
      properties:
        id:
          type: integer
          format: int64
          description: identificador unico del documento
        nombre:
          type: string
          description: nombre del documento
        descripcion:
          type: string
          description: una breve descripcion del documento requerido
          
  ######################################
  # Catalogos del dominio
  ######################################
    TipoConvenio:
      description: corresponde al sector en el que se desempeña el convenio
      type: object
      required:
        - codigo
        - nombre
      properties:
        codigo:
          type: integer
          format: int64
        nombre:
          type: string
  ####################
  # Corresponde al dominio de demograficos
  ####################
    Direccion:
      type: object
      description: entidad que define la ubicacion geografica de quien la referencie
      required:
        - id
        - direccion
        - ciudad
        - telefono
      properties:
        id:
          type: integer
          format: int64
        direccion:
          type: string
        ciudad:
          type: string
        telefono:
          type: string

  ####################
  # Common parameters
  ####################
  parameters:
    offsetParam:
      name: offset
      in: query
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before returning the results
    limitParam:
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: The number of items to return
    idDocumentacion:
      in: path
      name: idDocumentacion
      schema:
        type: integer
        format: int32
      description: corresponde al id de la documentacion requerida
    nit:
      in: query
      name: nit
      schema:
        type: string
      description: codigo unico con el que figura el convenio ante el estado

  #########################
  # Common link definitions
  # See: https://swagger.io/docs/specification/links/
  #########################
  links: {}

  #########################
  # Common callback definitions
  # See: https://swagger.io/docs/specification/callbacks/
  #########################
  callbacks: {}