# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: Empleados
  description: Este es el dominio de empleados para gataian proyecto recursos humanos
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    Requisito:
      type: object
      required: 
        - id
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
    Perfil:
      type: object
      required: 
        - id
        - areaNegocio
        - nombre
        - profesion
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        areasDependencia:
          type: array
          items:
            $ref: '#/components/schemas/AreaNegocio'
        requisitos:
          type: array
          items:
            $ref: '#/components/schemas/Requisito'
        profesion:
          $ref: '#/components/schemas/Profesion'
        
    Contacto:
      type: object
      description: contacto para comunicarse en caso de que suceda alguna emergencia con el empleado 
      required:
        - id
        - nombre
        - direccion
      properties:
        id:
          type: integer
          format: int64
        nombres:
          type: string
        apellidos:
          type: string
        direccion:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominioDemografico-1.0.0-domain.yaml#/components/schemas/Direccion'
        parentesco:
          $ref: '#/components/schemas/Parentesco'
          
    
    AreaNegocio:
      type: object
      required: 
        - id
        - nombre
        - cargos
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        requerimientos:
          type: array
          items:
            $ref: '#/components/schemas/RequerimientosArea'
    Empleado:
      type: object
      required:
        - id
        - cargo
        - nombres
        - apellidos
        - tipoDocumento
        - numeroDocumento
        - estado
        - genero
      properties:
        id:
          type: integer
          format: int64
        nombres:
          type: string
        apellidos:
          type: string
        cargo:
          $ref: '#/components/schemas/Cargo'
        profeciones:
          type: array
          items: 
            $ref: '#/components/schemas/Profesion'
        documentos:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Ingresos-1.0.0.yaml#/components/schemas/Documento'
        tipoDocumento:
          $ref: '#/components/schemas/TipoDocumento'
        numeroDocumento:
          type: string
        estado:
          type: string
        direccion:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominioDemografico-1.0.0-domain.yaml#/components/schemas/Direccion'
        genero:
          type: string
          description: >
            Genero del empleado como esta en su documento de identificacion:
              * F: FEMENINO
              * M: MASCULINO
          enum: [F,M]
        contactoEmergencia:
          $ref: '#/components/schemas/Contacto'
        numeroCuenta:
          type: string
        banco:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominiConvenios-1.0.0.yaml#/components/schemas/Convenio'
        eps:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominiConvenios-1.0.0.yaml#/components/schemas/Convenio'
        cesantias:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominiConvenios-1.0.0.yaml#/components/schemas/Convenio'
        arl:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominiConvenios-1.0.0.yaml#/components/schemas/Convenio'
        capacitaciones:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Ingresos-1.0.0.yaml#/components/schemas/Capacitacion'
        fondoPenciones:
          $ref: 'https://raw.githubusercontent.com/manuelgonzalezb/domains/master/Gataian-DominiConvenios-1.0.0.yaml#/components/schemas/Convenio'
    Cargo:
      type: object
      description: define los cargos de la empresa
      required:
        - id
        - nombre
        - perfil
        - salario
        - areaNegocio
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        descripcion:
          type: string
        perfil:
          $ref: '#/components/schemas/Perfil'
        areaNegocio:
          $ref: '#/components/schemas/AreaNegocio'
        salario:
          type: number
          format: double
          
    Profesion:
      type: object
      required:
        - id
        - nombre
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
          
    Vacante:
      type: object
      required:
        - id
        - cargo
        - fechaCreacion
      properties:
        id:
          type: integer
          format: int64
        descripcion:
          type: string
        cargo:
          $ref: '#/components/schemas/Cargo'
        fechaCreacion:
          type: string
          format: date-time
          
    RequerimientosArea:
      type: object
      required:
        - id
        - nombre
        - tiempoAtencion
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        tiempoAtencion:
          type: integer
          format: int32
          description: tiempo expresado en minutos en el que tarda el area en resolver el requerimiento 


  ####################
  # Catalogos
  ####################
    Parentesco:
      type: object
      required:
        - id
        - nombre
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
    TipoDocumento:
      type: object
      required: 
        - id
        - codigo
        - descripcion
      properties:
        id:
          type: integer
          format: int64
        codigo:
          type: string
        descripcion:
          type: string
  ####################
  # Common parameters
  ####################
  parameters:
    offsetParam:
      name: offset
      in: query
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before returning the results
    limitParam:
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: The number of items to return