# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: GATAIAN dominio ingresos 
  description: Este es el dominio de ingresos para la app Recursos humanos GATAIAN
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
    PruebaIngreso:
      type: object
      required: 
        - id
        - postulado
        - idSolicitud
        - documento
      properties:
        id:
          type: integer
          format: int64
        postulado:
          $ref: '#/components/schemas/Postulado'
        idSolicitud:
          type: integer
          format: int64
        documento:
          $ref: '#/components/schemas/Documento'
          
    SolicitudIngreso:
      type: object
      required: 
        - solicitante
        - postulado
        - areaNegocio
        - perfil
        - estado
        - fechaIngreso
        - fechaContratacion
        - detalleSolicitud
        - fechaSolicitud
      properties:
        solicitante:
          type: string ##manuel
        postulado:
          type: array
          items:
            $ref: '#/components/schemas/Postulado'
        areaNegocio:
          type: string ##Manuel
        perfil:
          type: string
        estado:
          type: string
        fechaIngreso:
          type: string
          format: date-time           
        fechaContratacion:
          type: string
          format: date-time
        detalleSolicitud:
          type: array
          items:
            $ref: '#/components/schemas/DetalleSolicitud' 
        fechaSolicitud:
          type: string
          format: date-time            

    Postulado:
      type: object
      required:
        - fechaEntrevista
        - nombre
        - apellidos
        - tipoDocumento
        - numeroDocumento
        - estado
        - entrevista
        - direccion
        - curriculum
      properties:
        fechaEntrevista:
          type: string
          format: date-time
        nombre:
          type: string
        apellidos:
          type: string
        tipoDocumento:
          $ref: '#/components/schemas/TipoDocumento'
        numeroDocumento:
          type: string
        estado:
          type: string
        entrevista:
          type: array
          items:
            $ref: '#/components/schemas/Entrevista'
        direccion:
          $ref: '#/components/schemas/Direccion'
        curriculum: 
          $ref: '#/components/schemas/Documento'
    
    Contrato:
      type: object
      required:
        - fechaCaducidad
        - tipoContrato
        - salarioAsignado
        - fechaIngreso
        - empleado
        - cargo
        - areaNegocio
        - clausula
      properties:
        fechaCaducidad:
          type: string
          format: date-time
        tipoContrato:
          type: array
          items:
            $ref: '#/components/schemas/TipoContrato'
        salarioAsignado:
          type: string
          format: money
        fechaIngreso:
          type: string
          format: date-time     
        empleado:
          type: string 
        clausula:
          type: array
          items:
            $ref: '#/components/schemas/Clausula'            

          
    Entrevista:
      type: object
      required:
        - calificacion
        - empleadoRealizoEntrevista
        - areaNegocio
        - privacidad
        - idPostulado
        - fechaRealizacion
        - comentariosEntrevista
        - pruebaIngreso
        - vacante
      properties:
        calificacion:
          type: integer
          format: int32
        areaNegocio:
          type: array
          items:
            type: string #manuel
        privacidad:
          type: string
        fechaRealizacion:
          type: string
          format: date-time   
        comentariosEntrevista:
          type: string
        pruebaIngreso:
          type: array
          items:
            $ref: '#/components/schemas/PruebaIngreso'  

          
    Clausula:
      type: object
      required:
        - id
        - termino
        - periodo
        - fechaCreacion
        - fechaActualizacion
      properties:
        id:
          type: integer
          format: int64
        termino:
          type: string
        periodo:
          type: string #catalogo
        fechaCreacion:
          type: string
          format: date-time    
        fechaActualizacion:
          type: string
          format: date-time              
 
    
    Documento:
      type: object
      required:
        - id
        - rutaAlmacenamiento
        - idEmpleado
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        rutaAlmacenamiento:
          type: string
        empleado:
          type: string #manuel
          
    DetalleSolicitud:
      type: object
      required:
        - id
        - empleadoSolicitante
        - fechaSolicitud
        - fechaFinalizacion
        - requerimientoArea
        - responsable
        - aprobacion
        - estadoSolicitud
      properties:
        id:
          type: integer
          format: int64
        fechaFinalizacion: 
          type: string
          format: date-time
        requerimientoArea:
          type: array
          items:
            type: string #manuel
        responsable:
          type: string #manuel
        aprobacion: 
          type: string
          enum: [pendiente, aprobado, rechazado]

          
    Capacitacion:
      type: object
      required:
        - id
        - nombre
        - descripcion
        - certificacion
        - costo
        - monto
        - areaNegocio
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        descripcion:
          type: string
        certificacion:
          type: boolean
        costo:
          type: boolean
        monto:
          type: string 
          format: money
        areaNegocio:
          type: array
          items:
            type: string #manuel 
        convenios:
          type: string #manuel
          
          
  ######################################
  # Catalogos del dominio
  ######################################
    TipoDocumento:
      description: corresponde al tipo de documento de la persona
      type: object
      required:
        - codigo
        - nombre
      properties:
        codigo:
          type: integer
          format: int64
        nombre:
          type: string

    TipoContrato:
      description: corresponde al tipo de contrato de la persona
      type: object
      required:
        - codigo
        - nombre
      properties:
        codigo:
          type: integer
          format: int64
        nombre:
          type: string   
  ####################
  # Corresponde al dominio de demograficos
  ####################
    Direccion:
      type: object
      description: entidad que define la ubicacion geografica de quien la referencie
      required:
        - id
        - direccion
        - ciudad
        - telefono
      properties:
        id:
          type: integer
          format: int64
        direccion:
          type: string
        ciudad:
          type: string
        telefono:
          type: string
  parameters:
    offsetParam:
      name: offset
      in: query
      schema:
        type: integer
        minimum: 0
      description: The number of items to skip before returning the results
    limitParam:
      in: query
      name: limit
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: The number of items to return



  #########################
  # Common link definitions
  # See: https://swagger.io/docs/specification/links/
  #########################
  links: {}

  #########################
  # Common callback definitions
  # See: https://swagger.io/docs/specification/callbacks/
  #########################
  callbacks: {}